# Generated by Django 5.0.4 on 2024-04-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_points_solution_points_task_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
